/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ShellListRouteImport } from './routes/_shell._list'
import { Route as DevComponentsRouteImport } from './routes/dev.components'
import { Route as ShellListIndexRouteImport } from './routes/_shell._list.index'
import { Route as ShellListTTodoIdRouteImport } from './routes/_shell._list.t.$todoId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellListRoute = ShellListRouteImport.update({
  id: '/_list',
  getParentRoute: () => ShellRoute,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellListIndexRoute = ShellListIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellListRoute,
} as any)
const ShellListTTodoIdRoute = ShellListTTodoIdRouteImport.update({
  id: '/t/$todoId',
  path: '/t/$todoId',
  getParentRoute: () => ShellListRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellListIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/components': typeof DevComponentsRoute
  '/t/$todoId': typeof ShellListTTodoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellListIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dev/components': typeof DevComponentsRoute
  '/t/$todoId': typeof ShellListTTodoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_shell/_list': typeof ShellListRouteWithChildren
  '/dev/components': typeof DevComponentsRoute
  '/_shell/_list/': typeof ShellListIndexRoute
  '/_shell/_list/t/$todoId': typeof ShellListTTodoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign-in' | '/sign-up' | '/dev/components' | '/t/$todoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign-in' | '/sign-up' | '/dev/components' | '/t/$todoId'
  id:
    | '__root__'
    | '/_shell'
    | '/sign-in'
    | '/sign-up'
    | '/_shell/_list'
    | '/dev/components'
    | '/_shell/_list/'
    | '/_shell/_list/t/$todoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  DevComponentsRoute: typeof DevComponentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_list': {
      id: '/_shell/_list'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellListRouteImport
      parentRoute: typeof ShellRoute
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_list/': {
      id: '/_shell/_list/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellListIndexRouteImport
      parentRoute: typeof ShellListRoute
    }
    '/_shell/_list/t/$todoId': {
      id: '/_shell/_list/t/$todoId'
      path: '/t/$todoId'
      fullPath: '/t/$todoId'
      preLoaderRoute: typeof ShellListTTodoIdRouteImport
      parentRoute: typeof ShellListRoute
    }
  }
}

interface ShellListRouteChildren {
  ShellListIndexRoute: typeof ShellListIndexRoute
  ShellListTTodoIdRoute: typeof ShellListTTodoIdRoute
}

const ShellListRouteChildren: ShellListRouteChildren = {
  ShellListIndexRoute: ShellListIndexRoute,
  ShellListTTodoIdRoute: ShellListTTodoIdRoute,
}

const ShellListRouteWithChildren = ShellListRoute._addFileChildren(
  ShellListRouteChildren,
)

interface ShellRouteChildren {
  ShellListRoute: typeof ShellListRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellListRoute: ShellListRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  DevComponentsRoute: DevComponentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
